-- デモ用の見本データ（実際の学習記録ではありません）
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 1;
UPDATE question SET topic = 'import' WHERE chapter = 1 AND number = 2;
UPDATE question SET topic = 'mainメソッド' WHERE chapter = 1 AND number = 3;
UPDATE question SET topic = 'javaコマンド' WHERE chapter = 1 AND number = 4;
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 5;
UPDATE question SET topic = 'import' WHERE chapter = 1 AND number = 6;
UPDATE question SET topic = 'mainメソッド' WHERE chapter = 1 AND number = 7;
UPDATE question SET topic = 'javaコマンド' WHERE chapter = 1 AND number = 8;
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 9;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 1;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 2;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 3;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 4;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 5;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 6;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 7;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 8;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 9;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 10;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 11;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 12;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 13;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 14;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 15;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 16;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 17;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 18;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 19;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 20;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 21;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 22;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 23;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 24;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 25;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 26;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 27;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 28;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 29;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 30;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 31;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 32;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 33;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 34;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 35;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 36;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 37;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 38;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 39;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 40;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 41;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 42;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 43;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 44;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 1;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 2;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 3;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 4;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 5;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 6;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 7;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 8;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 9;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 10;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 11;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 12;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 13;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 14;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 15;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 16;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 17;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 18;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 19;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 20;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 21;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 22;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 23;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 24;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 25;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 26;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 27;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 28;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 29;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 30;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 31;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 32;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 33;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 34;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 35;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 36;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 37;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 38;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 39;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 40;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 41;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 42;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 43;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 1;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 2;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 3;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 4;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 5;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 6;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 7;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 8;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 9;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 10;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 11;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 12;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 13;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 14;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 15;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 16;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 17;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 18;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 19;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 20;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 21;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 22;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 23;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 24;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 25;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 26;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 27;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 28;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 29;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 30;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 31;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 32;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 33;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 34;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 35;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 36;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 37;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 38;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 39;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 40;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 1;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 2;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 3;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 4;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 5;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 6;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 7;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 8;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 9;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 10;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 11;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 12;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 13;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 14;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 15;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 16;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 17;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 18;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 19;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 20;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 21;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 22;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 23;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 24;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 25;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 26;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 1;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 2;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 3;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 4;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 5;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 6;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 7;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 8;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 9;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 10;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 11;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 12;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 13;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 14;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 15;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 16;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 17;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 18;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 19;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 20;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 21;
UPDATE question SET topic = 'オーバーライド' WHERE chapter = 6 AND number = 22;
UPDATE question SET topic = 'インタフェース' WHERE chapter = 6 AND number = 23;
UPDATE question SET topic = 'record' WHERE chapter = 6 AND number = 24;
UPDATE question SET topic = '継承' WHERE chapter = 6 AND number = 25;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 1;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 2;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 3;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 4;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 5;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 6;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 7;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 8;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 9;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 10;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 11;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 12;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 13;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 14;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 15;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 16;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 17;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 18;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 19;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 20;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 21;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 22;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 23;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 24;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 25;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 26;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 27;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 28;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 29;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 30;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 31;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 32;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 33;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 34;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 35;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 36;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 37;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 38;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 39;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 40;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 41;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 42;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 43;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 44;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 45;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 46;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 47;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 48;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 49;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 50;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 51;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 52;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 53;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 54;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 55;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 56;
UPDATE question SET topic = '例外' WHERE chapter = 7 AND number = 57;
UPDATE question SET topic = 'try-with-resources' WHERE chapter = 7 AND number = 58;
UPDATE question SET topic = 'チェック例外' WHERE chapter = 7 AND number = 59;
UPDATE question SET topic = 'multi-catch' WHERE chapter = 7 AND number = 60;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -14, CURRENT_TIMESTAMP), DATEADD('DAY', -14, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -14, CURRENT_TIMESTAMP), DATEADD('DAY', -14, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -13, CURRENT_TIMESTAMP), DATEADD('DAY', -13, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -13, CURRENT_TIMESTAMP), DATEADD('DAY', -13, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -12, CURRENT_TIMESTAMP), DATEADD('DAY', -12, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -11, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -11, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -11, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -10, CURRENT_TIMESTAMP), DATEADD('DAY', -10, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 1 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 2 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), '仕様を覚えていなかった', 'knowledge' FROM question WHERE chapter = 2 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -6, CURRENT_TIMESTAMP), DATEADD('DAY', -6, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 2 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 2 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 2 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 21;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 22;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 2 AND number = 23;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 24;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 2 AND number = 25;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 2 AND number = 26;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 27;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 2 AND number = 28;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 29;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 30;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 3 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 3 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 3 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 3 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 3 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '仕様を覚えていなかった', 'knowledge' FROM question WHERE chapter = 3 AND number = 21;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '仕様を覚えていなかった', 'knowledge' FROM question WHERE chapter = 3 AND number = 22;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 23;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 3 AND number = 24;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 25;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 4 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 4 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 4 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 4 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 4 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 4 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 4 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 5 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 5 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 5 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 5 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, FALSE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 9;
