-- デモ用の見本データ（実際の学習記録ではありません）
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 1;
UPDATE question SET topic = 'import' WHERE chapter = 1 AND number = 2;
UPDATE question SET topic = 'mainメソッド' WHERE chapter = 1 AND number = 3;
UPDATE question SET topic = 'javaコマンド' WHERE chapter = 1 AND number = 4;
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 5;
UPDATE question SET topic = 'import' WHERE chapter = 1 AND number = 6;
UPDATE question SET topic = 'mainメソッド' WHERE chapter = 1 AND number = 7;
UPDATE question SET topic = 'javaコマンド' WHERE chapter = 1 AND number = 8;
UPDATE question SET topic = 'package' WHERE chapter = 1 AND number = 9;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 1;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 2;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 3;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 4;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 5;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 6;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 7;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 8;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 9;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 10;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 11;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 12;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 13;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 14;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 15;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 16;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 17;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 18;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 19;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 20;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 21;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 22;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 23;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 24;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 25;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 26;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 27;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 28;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 29;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 30;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 31;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 32;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 33;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 34;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 35;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 36;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 37;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 38;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 39;
UPDATE question SET topic = 'テキストブロック' WHERE chapter = 2 AND number = 40;
UPDATE question SET topic = '基本データ型' WHERE chapter = 2 AND number = 41;
UPDATE question SET topic = 'var' WHERE chapter = 2 AND number = 42;
UPDATE question SET topic = 'String' WHERE chapter = 2 AND number = 43;
UPDATE question SET topic = 'StringBuilder' WHERE chapter = 2 AND number = 44;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 1;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 2;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 3;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 4;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 5;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 6;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 7;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 8;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 9;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 10;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 11;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 12;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 13;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 14;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 15;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 16;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 17;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 18;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 19;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 20;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 21;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 22;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 23;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 24;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 25;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 26;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 27;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 28;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 29;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 30;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 31;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 32;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 33;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 34;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 35;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 36;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 37;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 38;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 39;
UPDATE question SET topic = 'インクリメント' WHERE chapter = 3 AND number = 40;
UPDATE question SET topic = '演算子' WHERE chapter = 3 AND number = 41;
UPDATE question SET topic = 'if文' WHERE chapter = 3 AND number = 42;
UPDATE question SET topic = 'switch式' WHERE chapter = 3 AND number = 43;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 1;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 2;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 3;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 4;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 5;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 6;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 7;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 8;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 9;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 10;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 11;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 12;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 13;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 14;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 15;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 16;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 17;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 18;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 19;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 20;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 21;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 22;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 23;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 24;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 25;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 26;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 27;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 28;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 29;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 30;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 31;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 32;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 33;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 34;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 35;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 36;
UPDATE question SET topic = '配列' WHERE chapter = 4 AND number = 37;
UPDATE question SET topic = '多次元配列' WHERE chapter = 4 AND number = 38;
UPDATE question SET topic = 'for文' WHERE chapter = 4 AND number = 39;
UPDATE question SET topic = '拡張for文' WHERE chapter = 4 AND number = 40;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 1;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 2;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 3;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 4;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 5;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 6;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 7;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 8;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 9;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 10;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 11;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 12;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 13;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 14;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 15;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 16;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 17;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 18;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 19;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 20;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 21;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 22;
UPDATE question SET topic = '可変長引数' WHERE chapter = 5 AND number = 23;
UPDATE question SET topic = 'static' WHERE chapter = 5 AND number = 24;
UPDATE question SET topic = 'メソッド' WHERE chapter = 5 AND number = 25;
UPDATE question SET topic = 'オーバーロード' WHERE chapter = 5 AND number = 26;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1272, CAST(DATEADD('DAY', -14, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -14, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 738, CAST(DATEADD('DAY', -13, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -13, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 1 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 739, CAST(DATEADD('DAY', -13, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -13, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1321, CAST(DATEADD('DAY', -12, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -12, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1218, CAST(DATEADD('DAY', -11, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1219, CAST(DATEADD('DAY', -11, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1222, CAST(DATEADD('DAY', -11, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1223, CAST(DATEADD('DAY', -11, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -11, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1224, CAST(DATEADD('DAY', -11, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -11, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 1 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1335, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1338, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 2 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1340, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1343, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1345, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1346, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1347, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1349, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -8, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1275, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1278, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1281, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 2 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1284, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 2 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1285, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1288, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1289, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1292, CAST(DATEADD('DAY', -7, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -7, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 487, CAST(DATEADD('DAY', -6, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -6, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 488, CAST(DATEADD('DAY', -6, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -6, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1398, CAST(DATEADD('DAY', -5, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1400, CAST(DATEADD('DAY', -5, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -5, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 2 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1403, CAST(DATEADD('DAY', -5, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 21;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1404, CAST(DATEADD('DAY', -5, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 22;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1405, CAST(DATEADD('DAY', -5, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -5, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 23;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1211, CAST(DATEADD('DAY', -4, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -4, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 24;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 724, CAST(DATEADD('DAY', -3, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -3, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 2 AND number = 25;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 727, CAST(DATEADD('DAY', -3, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -3, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 26;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1335, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 27;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1337, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 28;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1340, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 2 AND number = 29;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1341, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 2 AND number = 30;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 422, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 425, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 426, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 3 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 427, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 3 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 430, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 3 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 432, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 435, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 3 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 436, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 439, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 442, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 3 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 445, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 448, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 3 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 450, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1342, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1343, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1344, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1345, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 3 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1346, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1348, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1351, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1353, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 3 AND number = 21;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1356, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '用語の意味があいまい', 'knowledge' FROM question WHERE chapter = 3 AND number = 22;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1357, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 23;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1360, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 3 AND number = 24;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1363, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 3 AND number = 25;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 451, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 453, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 456, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 457, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 4 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 458, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 461, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 462, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 465, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 466, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 469, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 471, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 474, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1366, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 13;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1369, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 14;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1370, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 15;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1371, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 4 AND number = 16;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1372, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 4 AND number = 17;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1373, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 4 AND number = 18;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1375, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 4 AND number = 19;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1376, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '動作の流れを追えていなかった', 'understanding' FROM question WHERE chapter = 4 AND number = 20;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 477, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 5 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 422, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), 'APIの戻り値を勘違い', 'knowledge' FROM question WHERE chapter = 5 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 423, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 424, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 426, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '仕様を覚えていなかった', 'knowledge' FROM question WHERE chapter = 5 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 429, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 5 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1321, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '型の扱いを理解しきれていない', 'understanding' FROM question WHERE chapter = 5 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1323, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1325, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), 'セミコロンの位置を見落とした', 'careless' FROM question WHERE chapter = 5 AND number = 9;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1327, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '仕様を覚えていなかった', 'knowledge' FROM question WHERE chapter = 5 AND number = 10;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, TRUE, DATEADD('MINUTE', 1330, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 5 AND number = 11;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 1, FALSE, DATEADD('MINUTE', 1333, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -2, CURRENT_DATE), '問題文の条件を読み飛ばした', 'careless' FROM question WHERE chapter = 5 AND number = 12;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 431, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 1;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 432, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 2;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 434, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 3;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 437, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 4;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 439, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 5;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 440, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 6;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 442, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 7;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 443, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 8;
INSERT INTO attempt (question_id, round, correct, answered_at, answered_on, note, cause) SELECT id, 2, TRUE, DATEADD('MINUTE', 444, CAST(DATEADD('DAY', -1, CURRENT_DATE) AS TIMESTAMP)), DATEADD('DAY', -1, CURRENT_DATE), NULL, NULL FROM question WHERE chapter = 1 AND number = 9;
