CREATE TABLE IF NOT EXISTS question(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter INT NOT NULL,           -- 章
    number  INT NOT NULL,           -- 問題番号
    topic   VARCHAR(50),            -- record / ラムダ式 / 例外　など
    UNIQUE (chapter, number)
);

CREATE TABLE IF NOT EXISTS attempt(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INT NOT NULL,
    round       INT NOT NULL,       -- 何周目
    correct     BOOLEAN NOT NULL,
    answered_at TIMESTAMP,
    note        VARCHAR(500),       -- 間違えた理由
    FOREIGN KEY (question_id) REFERENCES question(id)
);
CREATE TABLE IF NOT EXISTS review_schedule(
    question_id INT PRIMARY KEY,
    next_due    DATE NOT NULL,    -- 次に解く日
    interval_d  INT NOT NULL,     -- 現在の間隔（日）
    updated_at  TIMESTAMP,
    FOREIGN KEY (question_id) REFERENCES question(id)
);

-- 穴の原因: knowledge（知識）/ understanding（理解）/ careless（ケアレスミス）
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS cause VARCHAR(20);

-- 解いた日。時刻が分からない過去分は answered_at を NULL にして、ここだけ入れる。
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS answered_on DATE;
UPDATE attempt SET answered_on = CAST(answered_at AS DATE)
 WHERE answered_on IS NULL AND answered_at IS NOT NULL;
